name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Cố định bản Ubuntu 22.04 ổn định để tránh lỗi phiên bản mới

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: kivy/buildozer-action@v1
      with:
        command: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
