name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies & Buildozer
      run: |
        sudo apt update
        # Cài đặt thêm các gói 32-bit và công cụ nền tảng để Aidl và các SDK tools hoạt động chính xác
        sudo apt install -y git zip unzip openjdk-17-jdk libltdl-dev libffi-dev \
          libc6:i386 libstdc++6:i386 zlib1g:i386
        pip install --upgrade pip
        pip install --upgrade buildozer cython==0.29.34

    - name: Build with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
